### ISSUE TITLE
1025 file descriptors

### ISSUE THREAD

**Issue by Fux002** [schlitzered/pyredis#3]
Hi i need a redis python library that uses poll or epoll to connect rather than select.

On linux select only allows 1024 file descriptors, i need a lot more. Does this package use this and if not is it difficult to convert?

**Comment by schlitzered** [comment]
this packages is not using any async selector at all.

i guess you hit the "select" issue of the other , more popular, python redis implementation?

this library is not suffering from this issue, because it makes no sense in blocking code to use a selector like "select", "poll", "epoll" or "kqueue". 

instead this library sets a timeouts, which can be configured, on the socket to make sure the code will not block forever if something is wrong with the socket.

**Comment by schlitzered** [comment]
The Pool classes are thread save. and there is a dedicated subscribe client.

please see the official documentation for more details:

https://pyredis.readthedocs.io/en/latest/
