### ISSUE TITLE
cluster client doesn't have pipeline implementation

### ISSUE THREAD

**Issue by keajer** [schlitzered/pyredis#7]
maybe add your bulk mechanism into cluster client as well?

**Comment by schlitzered** [comment]
hi,

there is no easy/sane way to implement bulk mode with redis cluster.

the problem is how redis cluster works, during shard migration.

if a shard is migrated, requests might be answered with a "MOVED" and "ASK" ask response, which will tell you to ask another cluster member, that might now is responsible for the key in question.

so it is not possible to simply send requests to the wire, and collect the responses later, which bulk mode is doing (as well as the pipeline mode of the python redispy implementation). because there might be actionthat need to be done.

this is why there is no bulk mode for redis cluster in this library.

please also see https://redis.io/topics/cluster-spec, which describes how redis cluster is working internally.

Kind Regards
